[colors]
left_top_bg = { r = 44, g = 44, b = 44 }
chat_bg = { r = 20, g = 20, b = 20 }
right_bg = { r = 10, g = 10, b = 10 }
input_bg = { r = 50, g = 50, b = 50 }
status_bg = { r = 36, g = 36, b = 36 }
text_fg = { r = 150, g = 180, b = 225 }
muted_fg = { r = 185, g = 185, b = 185 }
active_fg = { r = 255, g = 255, b = 255 }
